#https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress
#https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-multi-ssl#google-managed-certs_1

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: <FQDN>
spec:
    domains: 
      - <FQDN>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-gke-ingress
  annotations:
    networking.gke.io/managed-certificates: "<FQDN>"
spec:
  rules:
  - host: <FQDN>
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: jenkins
            port:
              number: 80