#https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress
#https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-multi-ssl#google-managed-certs_1

apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: jenkins-gke.taboosubject.pl
spec:
    domains: 
      - jenkins-gke.taboosubject.pl
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-gke-ingress
  annotations:
    networking.gke.io/managed-certificates: "jenkins-gke.taboosubject.pl"
spec:
  rules:
  - host: jenkins-gke.taboosubject.pl
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: jenkins
            port:
              number: 80